<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.1</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <Target Name="SetInformationalVersion" BeforeTargets="GenerateAssemblyInfo">
    <Exec Command="git rev-parse --short=7 HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true" StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitShortHash" />
      <Output TaskParameter="ExitCode" PropertyName="GitExitCode" />
    </Exec>

    <PropertyGroup Condition="'$(GitExitCode)' == '0' And '$(GitShortHash)' != ''">
      <InformationalVersion>$(Version)+$(GitShortHash)</InformationalVersion>
    </PropertyGroup>
  </Target>

</Project>
